CFLAGS=-DOSX -O -Wall
NVCCFLAGS=-DOSX -O2 -Xptxas -v -Xcompiler -Wall
NVCC=nvcc
CXX=g++

all: memtestG80

clean:
	rm -f *.o
	rm -f memtestG80

memtestG80_core.o: memtestG80_core.cu memtestG80_core.h
	$(NVCC) -c $(NVCCFLAGS) -o memtestG80_core.o memtestG80_core.cu



memtestG80: memtestG80_core.o memtestG80_cli.cu
	$(NVCC) $(NVCCFLAGS) -o memtestG80 memtestG80_core.o memtestG80_cli.cu

