ZLIB_DIR=zlib/linux64
CUDA_DIR=/usr/local/cuda/lib64
CFLAGS=-DLINUX -O -Wall -m64
NVCCFLAGS=-DLINUX -L$(ZLIB_DIR) -L$(CUDA_DIR) -O2 -Xptxas -v -Xcompiler -Wall -m64
NVCC=nvcc
CXX=g++

all: memtestG80

clean:
	rm -f *.o
	rm -f memtestG80

memtestG80_core.o: memtestG80_core.cu memtestG80_core.h
	$(NVCC) -c $(NVCCFLAGS) -o memtestG80_core.o memtestG80_core.cu



memtestG80: memtestG80_core.o memtestG80_cli.cu
	$(NVCC) $(NVCCFLAGS) -o memtestG80 memtestG80_core.o memtestG80_cli.cu

